{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 59,
   "id": "5e5afe2e-ec32-49d9-8f8c-61f1706c1222",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[[[1, 2], [5, 5], [3, 2], [3, 3], [1, 5], [4, None], [2, 3], [3, 5], [1, 5], [3, 1], [4, 4], [2, None]], [[2.7, 6.6], [1.6, 3.0], [0.7, 3.3], [1.2, 4.1], [3.5, 4.5], [2.5, 2.5], [1.4, 3.4], [5.2, 6.3], [4.3, 5.2], [6.2, 6.7], [5.5, 6.9], [5.3, 5.3]]]\n",
      "\n",
      "[[[1, 3], [1, 2], [2, 3], [4, 3], [3, 5], [5, None], [4, 2], [5, None], [1, 4], [4, 3], [2, 1]], [[4.3, 6.0], [1.6, 3.9], [1.0, 3.7], [2.8, 4.5], [0.8, 4.6], [2.7, 2.7], [4.2, 7.9], [6.8, 6.8], [5.1, 8.2], [6.4, 8.6], [6.4, 7.9]]]\n",
      "\n",
      "[[[2, 2], [4, 1], [1, 5], [3, 4], [4, 5], [1, None], [4, 5], [5, None], [4, 3], [2, 3]], [[3.0, 7.1], [8.3, 10.3], [6.3, 10.2], [3.0, 3.6], [1.2, 3.7], [3.3, 3.3], [5.3, 6.8], [5.0, 5.0], [3.0, 5.2], [5.6, 6.9]]]\n",
      "\n",
      "[[[1, 5], [4, 2], [1, 2], [5, 2], [3, None], [2, 2], [6, 1], [4, None], [6, 1], [7, 5], [3, None], [5, 1], [2, 7], [7, 3], [1, 7]], [[4.68, 15.84], [16.07, 21.52], [3.64, 13.0], [11.35, 15.97], [2.89, 2.89], [5.04, 9.23], [14.76, 21.43], [8.7, 8.7], [4.97, 6.41], [17.83, 22.01], [6.47, 6.47], [7.16, 9.84], [0.69, 2.12], [10.2, 16.89], [1.78, 6.57]]]\n",
      "\n",
      "[[[1, 1], [2, None], [4, 7], [9, None], [3, 3], [1, 8], [5, 6], [9, 6], [5, 4], [6, 8], [7, 7], [4, 1], [6, 3], [4, None], [3, 9], [2, 7], [7, 8], [8, 4], [8, 4], [6, 2]], [[16.0, 21.0], [9.6, 9.6], [4.8, 10.2], [8.9, 8.9], [6.4, 7.4], [3.5, 10.3], [9.6, 13.2], [14.4, 15.3], [16.2, 16.6], [13.0, 16.0], [13.7, 19.0], [5.3, 11.1], [7.6, 11.9], [15.7, 15.7], [16.7, 17.3], [15.8, 16.4], [9.0, 22.9], [5.3, 7.0], [13.4, 16.2], [22.1, 28.7]]]\n",
      "\n"
     ]
    }
   ],
   "source": [
    "def heuristic_algorithm(fullpath):\n",
    "    import os\n",
    "    import pandas as pd\n",
    "    import numpy as np\n",
    "    from heapq import heappush, heappop, heapify\n",
    "    from heapdict import heapdict\n",
    "    # job structure \n",
    "    \n",
    "    # see https://github.com/DanielStutzbach/heapdict\n",
    "    # or directly !pip install HeapDict\n",
    "    # job structure\n",
    "\n",
    "    GAP = 1e-7\n",
    "    class Job:\n",
    "        '''structure for 1 job '''\n",
    "        def __init__(self, row):\n",
    "            '''input := df.iloc[idx, :]'''\n",
    "            self.id = row['Job ID']\n",
    "            self.due = row['Due Time']\n",
    "            self.next_op = 0 # True as complete, False as not yet processed\n",
    "            self.stage_pt = [row['Stage-1 Processing Time'], row['Stage-2 Processing Time']]\n",
    "            mfor1 = list(map(int, row['Stage-1 Machines'].split(',')))\n",
    "            if row['Stage-2 Machines'] is not np.nan:\n",
    "                mfor2 = list(map(int, row['Stage-2 Machines'].split(',')))\n",
    "            else: mfor2 = []\n",
    "            self.stage_mach = [mfor1, mfor2]\n",
    "            self.assign_mach = [None for _ in range(2)]\n",
    "            self.start_time = [-1 for _ in range(2)]\n",
    "            self.end_time = [-1 for _ in range(2)]\n",
    "\n",
    "        def __repr__(self):\n",
    "            return f'\\\n",
    "              * Job id: {self.id}\\n\\\n",
    "              * Due time:{self.due}\\n\\\n",
    "              stage 1: {self.assign_mach[0]}\\n\\\n",
    "                       {self.stage_pt[0]}, {self.stage_mach[0]}\\n\\\n",
    "              stage 2: {self.assign_mach[1]}\\n\\\n",
    "                       {self.stage_pt[1]}, {self.stage_mach[1]}'\n",
    "        __str__ = __repr__\n",
    "\n",
    "    class Jobs:\n",
    "        '''structure for multiple jobs' management'''\n",
    "        def __init__(self, n):\n",
    "            self.completion_times = np.zeros(n)\n",
    "            self.tardiness = np.zeros(n)\n",
    "            self.is_completed = np.full(n, False)\n",
    "            self.residual_times = np.zeros(n)\n",
    "            self.jobs = []\n",
    "\n",
    "        def get_RRDD(self):\n",
    "            if getattr(self, 'RRDD', None) is None:\n",
    "                self.RRDD = self.due_dates - np.min(self.due_dates)\n",
    "            return self.RRDD # static\n",
    "\n",
    "        def get_LST(self):\n",
    "            '''latest start time'''\n",
    "            self.LST = self.due_dates - self.residual_times\n",
    "            return self.LST\n",
    "\n",
    "        def add_jobs(self, data):\n",
    "            self.due_dates = data['Due Time'].to_numpy()\n",
    "            for i in range(len(data)):\n",
    "                row = data.iloc[i, :]\n",
    "                jobi = Job(row)\n",
    "                self.residual_times[i] = sum(jobi.stage_pt)\n",
    "                self.jobs.append(jobi)\n",
    "\n",
    "\n",
    "        def assign(self, job_name, mach, st):\n",
    "            '''job_name = (2, 0) means job 3 and op 1\n",
    "            note that job and op is 0-indexed as well as machines\n",
    "            op\n",
    "            '''\n",
    "            jobidx, op = job_name\n",
    "            job = self.jobs[jobidx]\n",
    "            self.completion_times[jobidx] = st + job.stage_pt[op]\n",
    "            self.residual_times[jobidx] -= job.stage_pt[op]\n",
    "            job.assign_mach[op] = mach\n",
    "            job.start_time[op] = st\n",
    "            job.end_time[op] = self.completion_times[jobidx]\n",
    "            job.next_op = op+1\n",
    "            if op == 1:\n",
    "                self.is_completed[jobidx] = True\n",
    "\n",
    "    class Machines:\n",
    "        def __init__(self, df):\n",
    "            '''pass the stage1, stage2 machine lists'''\n",
    "            mfor1 = df['Stage-1 Machines'].values.tolist()\n",
    "            mfor2 = df['Stage-2 Machines'].values.tolist()\n",
    "            mfor1 = [list(map(int, x.split(','))) for x in mfor1]\n",
    "            # print('mfor2', mfor2, type(mfor2))\n",
    "            mfor2 = [list(map(int, x.split(','))) for x in mfor2 if x is not np.nan]\n",
    "            mfor1 = [item for sublist in mfor1 for item in sublist]\n",
    "            mfor2 = [item for sublist in mfor2 for item in sublist]\n",
    "\n",
    "            self.number = max(max(mfor1), max(mfor2))\n",
    "            self.versatile = [mfor1.count(i+1) + mfor2.count(i+1) for i in range(self.number)]\n",
    "            self.holes = [[] for _ in range(self.number)]\n",
    "\n",
    "            self.fintime = [0 for _ in range(self.number)]\n",
    "            self.HL = [0 for _ in range(self.number)]\n",
    "\n",
    "\n",
    "        def _schedule(self, mach, job_name, st, proc_time):\n",
    "            '''mach is 0-indexed'''\n",
    "            display_name = tuple([x+1 for x in job_name])\n",
    "            # self.schedule[mach].append((f'{display_name}', round(end_time, 3)))\n",
    "            self.fintime[mach] = st + proc_time\n",
    "\n",
    "\n",
    "\n",
    "        def add_idle(self, mach, idle_time,\n",
    "                    hole_start, hole_end):\n",
    "            # self.schedule[mach].append((f'idle', round(hole_end)))\n",
    "            self.fintime[mach] += idle_time\n",
    "            # add hole\n",
    "            # len(self.schedule)-1 is the idx of this hole in schedule\n",
    "            hole = tuple([hole_start, hole_end])\n",
    "            self.holes[mach].append(hole)\n",
    "            self.HL[mach] += hole_end - hole_start\n",
    "\n",
    "        def schedule_hole(self, job_name, mach, hole_id, fill_end):\n",
    "            '''update and return updated average hole length'''\n",
    "            hole = self.holes[mach][hole_id]\n",
    "            hole_start, hole_end = hole\n",
    "            hole_length = hole_end - hole_start\n",
    "            if abs(hole_end - fill_end) < GAP:\n",
    "                # pop the hole by hole_id\n",
    "                self.holes[mach].pop(hole_id)\n",
    "            else:\n",
    "                self.holes[mach][hole_id] = tuple([fill_end, hole_end])\n",
    "            self.HL -= (fill_end - hole_start) # processing time\n",
    "            # display_name = tuple([x+1 for x in job_name])\n",
    "            return self.HL/len(self.holes)\n",
    "    \n",
    "    def make_Q(J):\n",
    "        Job_keys = []\n",
    "        for job_index in range(len(J.jobs)):\n",
    "            op1_pt, op2_pt = J.jobs[job_index].stage_pt\n",
    "            # 我覺得 due_dates 幾乎等於 total proc time的反而可以放後面(不太可能來得及，乾脆果斷放棄)\n",
    "            LST = J.get_LST()\n",
    "            if LST[job_index] <= GAP: # avoid division by zero error\n",
    "                lst_ratios = [0, 0]\n",
    "            else:\n",
    "                lst_ratios = [op1_pt / J.LST[job_index], op2_pt / J.LST[job_index]]\n",
    "            # preserve precedence:\n",
    "            lst_ratios[0] = max(lst_ratios)\n",
    "            # NOTE: min queue extracts by minimum value, so add a negative sign here\n",
    "            # (lst_ratio, job_index, job_op)\n",
    "            Job_keys.append((-lst_ratios[0], job_index, 0))\n",
    "            Job_keys.append((-lst_ratios[1], job_index, 1))\n",
    "        Q = Job_keys[:]\n",
    "        heapify(Q)\n",
    "        return Q\n",
    "\n",
    "    def getAvailMachs(J, M):\n",
    "        import numpy as np\n",
    "        bigM = M.number\n",
    "        bigN = len(J.jobs)\n",
    "        AvailMachs = np.full((bigN, 2, bigM),\n",
    "                             fill_value = False)\n",
    "        for i in range(bigN):\n",
    "            mfor1, mfor2 = J.jobs[i].stage_mach[0], J.jobs[i].stage_mach[1]\n",
    "            for m in mfor1:\n",
    "                AvailMachs[i][0][m-1] = True\n",
    "            for m in mfor2:\n",
    "                AvailMachs[i][1][m-1] = True\n",
    "        # indexing AvailMachs[i][j][m] to check if job (i,j) can be put on machine m (all ZERO-indexed)\n",
    "        return AvailMachs\n",
    "\n",
    "    def make_mQ(M):\n",
    "        Q = []\n",
    "        for m in range(M.number):\n",
    "            versatility = M.versatile[m]\n",
    "            Q.append([versatility, m])\n",
    "        return sorted(Q, key = lambda x:(x[0], x[1]))\n",
    "\n",
    "\n",
    "    def find_hole(job_name, \n",
    "              currjob, \n",
    "              J,\n",
    "              M, \n",
    "              Mach_Q, \n",
    "              AvailMachTable):\n",
    "        curr_jindex, curr_op = job_name \n",
    "        proc_time = currjob.stage_pt[curr_op]\n",
    "        def find_hole_helper():\n",
    "            for idx, curritem in enumerate(Mach_Q):\n",
    "                _, m_id = curritem\n",
    "                if not AvailMachTable[curr_jindex][curr_op][m_id]:\n",
    "                    continue\n",
    "                # find legal holes\n",
    "                if not M.holes[m_id]:\n",
    "                    continue\n",
    "                for hole_id, hole in enumerate(M.holes[m_id]):\n",
    "                    hole_start, hole_end = hole\n",
    "                    hole_length = hole_end - hole_start \n",
    "                    # enough length \n",
    "                    if hole_length - proc_time >= -GAP:\n",
    "                        # check legal precedence \n",
    "                        curr_hole_id = hole_id\n",
    "                        if curr_op == 1 and hole_start >= currjob.end_time[0]:\n",
    "                            return idx, m_id, curr_hole_id, hole_start + proc_time\n",
    "                        elif curr_op == 0: \n",
    "                            return idx, m_id, curr_hole_id, hole_start + proc_time\n",
    "                    # 一律從hole_start開始schedule，沒辦法的話就跳過（不然更新holes那邊變超麻煩）\n",
    "        res = find_hole_helper()\n",
    "        if not res:\n",
    "            # print(f'No result in finding a hole for {[x+1 for x in job_name]}')\n",
    "            return False\n",
    "        if res:\n",
    "            idx, m_id, hole_id, fill_end = res\n",
    "            #print(f'Schduling {m_id+1}, {M.holes[m_id][hole_id]} for {[x+1 for x in job_name]}')\n",
    "            #print(f'Original: {M.holes[m_id]}')\n",
    "            # idx是Queue中machine的位置\n",
    "            hole = M.holes[m_id][hole_id]\n",
    "            # print(hole)\n",
    "            hole_start, hole_end = hole\n",
    "            J.assign(job_name = job_name, \n",
    "                    mach = m_id, \n",
    "                    st = hole_start) \n",
    "            # update hole length and replace avg_hole_length \n",
    "            new_avg_hl = M.schedule_hole(\n",
    "                    job_name = job_name, \n",
    "                    mach = m_id, \n",
    "                    hole_id = hole_id, \n",
    "                    fill_end = fill_end)  \n",
    "            # print(f'Updated: {M.holes[m_id]}')\n",
    "            return True \n",
    "    \n",
    "    def heuristic(J, M): \n",
    "        # best_makepsan = sum(job_processing_time) for all jobs / |M|\n",
    "        # heperparameters \n",
    "        TOLRATIO = 0.3\n",
    "        Fail_Tolerance = 2\n",
    "        best_makespan = sum(job.stage_pt[0]+job.stage_pt[1] for job in J.jobs)/M.number\n",
    "        tolerance = best_makespan * TOLRATIO  # tolerance for idle time, if idle > tolerance, do not schedule the curr op in the current epoch. \n",
    "        #print(f'[INFO] {len(J.jobs)} jobs, {M.number} machines')\n",
    "        #print(f'[INFO] Tolerance: {tolerance:.2f}')\n",
    "\n",
    "        # Job_Q (lst_ratio, job_index, job_op) \n",
    "        Job_Q = make_Q(J)\n",
    "        # print(f'Job Queue: {Job_Q}')\n",
    "        # Mach_Q (versatility, avg_hole_length, m)\n",
    "        Mach_Q = make_mQ(M)\n",
    "        AvailMachs = getAvailMachs(J = J, M = M)\n",
    "\n",
    "\n",
    "        fails = [0 for _ in range(len(J.jobs))]\n",
    "        epoch = 0\n",
    "        while Job_Q:\n",
    "            epoch += 1\n",
    "            PERMIT = True\n",
    "            # step 3. extract_min() to get the job with minimal LST and its other attributes\n",
    "            _, curr_job_index, curr_op = heappop(Job_Q)\n",
    "            curr_job = J.jobs[curr_job_index]\n",
    "            op_proc_time = curr_job.stage_pt[curr_op]\n",
    "            job_name = (curr_job_index, curr_op)\n",
    "\n",
    "\n",
    "            # if curr_job has no second operation \n",
    "            if op_proc_time <= GAP and curr_op == 1: \n",
    "                J.assign(job_name = job_name, \n",
    "                        mach = None,\n",
    "                        st = curr_job.end_time[curr_op-1]) \n",
    "                # note that it's only possible for second operation to have proc time = 0\n",
    "                # so this doesn't trigger index error\n",
    "                continue \n",
    "            # step 4-1. calculate the best machine: find-hole\n",
    "            # 'job_name', 'currjob', and 'Mach_Q'\n",
    "            if find_hole(J = J, M = M,\n",
    "                         job_name = job_name, currjob = curr_job, Mach_Q = Mach_Q,\n",
    "                      AvailMachTable = AvailMachs):\n",
    "\n",
    "                continue\n",
    "\n",
    "\n",
    "            # step 4-2. if find-hole fails, calculate the best machine and schedule at the end \n",
    "            avail_machines_idx = [x-1 for x in curr_job.stage_mach[curr_op]]\n",
    "            curr_machine = min(avail_machines_idx, key = lambda x: (M.fintime[x], M.versatile[x], x))\n",
    "            # ARE THERE REASONS TO POSTPONE THE CURR OP?\n",
    "            if J.completion_times[curr_job_index] + op_proc_time > J.due_dates[curr_job_index] and curr_op == 1 and fails[curr_job_index] < Fail_Tolerance:\n",
    "                #print(f'[INFO] Job {curr_job_index+1} op {curr_op+1} will be tardy even if scheduled, queue last.')\n",
    "                curr_new_value = float('inf')\n",
    "                PERMIT = False\n",
    "\n",
    "            # ARE THERE REASONS TO POSTPONE THE CURR OP (if curr_op is second op)?\n",
    "            elif M.fintime[curr_machine] < J.completion_times[curr_job_index]:\n",
    "\n",
    "                idle = J.completion_times[curr_job_index] - M.fintime[curr_machine]\n",
    "                if idle > tolerance and curr_op == 1 and fails[curr_job_index] < Fail_Tolerance:\n",
    "                    #print(f'[INFO] Job {curr_job_index+1} op {curr_op+1} has idle {idle:.2f}, postpone it.')\n",
    "                    PERMIT = False\n",
    "                    if Job_Q:\n",
    "                        curr_new_value = Job_Q[0][0] + 3\n",
    "                    else:\n",
    "                        curr_new_value = 0 # the last one \n",
    "                else:\n",
    "                    #print(f'[INFO] Job {curr_job_index+1} op {curr_op+1} has idle {idle:.2f}.')\n",
    "\n",
    "                    M.add_idle( \n",
    "                    hole_start = M.fintime[curr_machine],\n",
    "                    hole_end =  J.completion_times[curr_job_index], \n",
    "                    mach = curr_machine, \n",
    "                    idle_time = idle)\n",
    "\n",
    "            if PERMIT:\n",
    "                # print(f'Scheduling {[x+1 for x in job_name]} on machine {curr_machine+1}\\'s end at {M.fintime[curr_machine]}')\n",
    "                J.assign(job_name = job_name, \n",
    "                    mach = curr_machine, \n",
    "                     st = M.fintime[curr_machine]\n",
    "                    ) \n",
    "                M._schedule(job_name = job_name, \n",
    "                   mach = curr_machine, \n",
    "                    proc_time = op_proc_time,\n",
    "                   st = M.fintime[curr_machine])\n",
    "                curr_new_value = J.get_LST()[curr_job_index]\n",
    "            else: \n",
    "                fails[curr_job_index] += 1\n",
    "            # print(f'{epoch} Fails Count:', fails)\n",
    "            # update the LST value and push it back to Q if the job has its second operation that hasn't been done\n",
    "            if not PERMIT:\n",
    "                heappush(Job_Q, (curr_new_value, curr_job_index, curr_op))\n",
    "                # it maintains the heap invariant, no need to heapify\n",
    "        return J, M\n",
    "    \n",
    "    def make_result(J):\n",
    "        '''pass in the resulted J'''\n",
    "        n = len(J.jobs)\n",
    "        machine, completion_time = [], []\n",
    "        for i in range(n):\n",
    "            if  J.jobs[i].assign_mach[1] is None:\n",
    "                op2_mach_id = None\n",
    "            else: op2_mach_id = J.jobs[i].assign_mach[1]+1\n",
    "            op1_mach_id = J.jobs[i].assign_mach[0]+1\n",
    "            op1_c_time = round(J.jobs[i].end_time[0], 3)\n",
    "            op2_c_time = round(J.jobs[i].end_time[1], 3)\n",
    "            machine.append([op1_mach_id, op2_mach_id])\n",
    "            completion_time.append([op1_c_time, op2_c_time])\n",
    "        assert len(machine) == len(completion_time) == n\n",
    "        return machine, completion_time\n",
    "    \n",
    "    instances = []\n",
    "    instances.append(pd.read_csv(fullpath))\n",
    "\n",
    "    df = instances[0]\n",
    "    M = Machines(df)\n",
    "    J = Jobs(len(df))\n",
    "    J.add_jobs(df)\n",
    "    heuristic(J = J, M = M)\n",
    "    Tardy_jobs = list(np.where(J.completion_times > J.due_dates)[0])\n",
    "    Tardy_jobs = [x+1 for x in Tardy_jobs]\n",
    "    Makespan = max(M.fintime)\n",
    "    Answers = list(make_result(J))\n",
    "    return Answers"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "738b435c-dd3d-4321-95fa-cdf03cef9240",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
